name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag caddy-porech-maxmind:$(date +%s)  --build-arg CADDY_VERSION=${{ vars.CADDYVERSION }}
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PAT }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the Docker image to the registry
      run: docker push -a caddy-porech-maxmind
